---
abstract: 'A file base extention of Test::Deep'
author:
  - 'G. Allen Morris III, <gam3@gam3.net>'
distribution_type: module
generated_by: 'Module::Install version 0.76'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-DeepFile
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.01
resources:
  license: http://dev.perl.org/licenses/
version: 0.001
